// Dummy book data for development

export const BOOKSHELF_DATA = [
    {
        id: 1,
        title: 'The Lord of the Rings',
        author: 'J.R.R. Tolkien',
        rating: 5,
        review: 'A classic fantasy series that has inspired many others.',
    },
    {
        id: 2,
        title: 'The Hobbit',
        author: 'J.R.R. Tolkien',
        rating: 5,
        review: 'A great introduction to the world of Middle Earth.',
    },
    {
        id: 3,
        title: 'Red Rising',
        author: 'Pierce Brown',
        rating: 4,
        review: 'A fantastic sci-fi series with a great main character.',
    }
];